- hosts: media-pc
  remote_user: moss
  become: yes
  become_method: sudo
  tasks:
  - name: Update repos to include bleeding edge stable
    apt_repository:
      repo: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
        - ppa:team-xbmc/ppa
        - ppa:mdeslaur/steamos
        - ppa:ubuntu-x-swat/updates
#steam needs eula fix https://askubuntu.com/questions/506909/how-can-i-accept-the-lience-agreement-for-steam-prior-to-apt-get-install?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
  - name: Update repositories cache and install packages in items
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
        - steam
        - kodi
        - xorg
        - steamos-xpad-dkms
        - lightdm
        - fluxbox
        - nautilus
  - name: Download MediaPC script
    get_url:
      url: https://raw.githubusercontent.com/Mossman1215/MediaPC-Script/master/loadAProgramLoop.sh
      dest: /usr/local/bin/loadAProgramLoop.sh
